### ISSUE TITLE
Missing Raymath functions

### ISSUE THREAD

**Issue by FishTheFirst** [electronstudio/jaylib-ffm#13]
Math functions present in Jaylib are missing in the Jaylib-ffm maven module.

Jaylib:
![image](https://github.com/user-attachments/assets/c3e6d346-8fc4-4406-b585-693d52dc9e6b)

Jaylib-ffm:
![image](https://github.com/user-attachments/assets/fddf72af-f32c-45ea-93d9-88f2eea0875a)
![image](https://github.com/user-attachments/assets/00515991-b4f3-4379-a1ce-d3c65bdb3ff7)
![image](https://github.com/user-attachments/assets/96540179-ee1f-485d-b697-963aa2098af6)

**Comment by electronstudio** [comment]
try this https://github.com/electronstudio/jaylib-ffm/commit/5dfa2e30a4a2adb528b256c6e608c84cfdcb25dd

**Comment by FishTheFirst** [comment]
Generated the builds with the 5.5 source and DLL, but still no vector functions. In fact, my build seems to be a few thousand lines short. I'm on win10 x64.
[out.zip](https://github.com/user-attachments/files/17950127/out.zip)

**Comment by electronstudio** [comment]
I don't know what's wrong with your build, but it seems to work for me.  I've added wrappers too.  https://github.com/electronstudio/jaylib-ffm/releases/tag/v5.5.0-1

**Comment by FishTheFirst** [comment]
Not sure either, but this new release works great, thanks!
